Traceback (most recent call last):
  File "/sandbox/code/errors_robust/runtime_err_20250611_171938_443179_runtime_err.py", line 2, in <module>
    value = 1/0
            ~^~
ZeroDivisionError: division by zero
